name: build
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: | 
          sudo apt-get -qq update
          sudo apt-get -qq install autoconf automake
      - name: autoconf 
        run: |
          ./bootstrap
      - name: Archive configure
        uses: actions/upload-artifact@v3
        with:
          name: store configure
          path: |
            **
