name: build
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: | 
          sudo apt-get -qq update
          sudo apt-get -qq install autoconf
      - name: autoconf 
        run: |
          ./bootstrap
      - name: Archive configure
        uses: actions/upload-artifact@v3
        with:
          name: store configure
          path: |
            Makefile.in
            aclocal.m4
            ar-lib
            autom4te.cache
            compile
            config.guess
            config.h.in
            config.sub
            configure
            depcomp
            install-sh
            ltmain.sh
            missing
            hidtest/Makefile.in
            pc/hidapi.pc.in
